routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'login' => true,
    'register' => true,
    'reset' => false,
    ]);

    Route::middleware(['XSS'])->group(function () {

    //Installation Part

    Route::get('/install','Installer\InstallerController@install')->name('install')->middleware('installer');

    Route::get('/install/info','Installer\InstallerController@info')->name('install.info');
    Route::get('/install/check/{param}','Installer\InstallerController@check')->name('install.check');
    Route::get('pre/install','Installer\InstallerController@preinstall')->name('preinstall');
    Route::post('/install/store','Installer\InstallerController@send');

    //Frontend Part

    Route::get('/', 'SiteController@index')->name('index');
    Route::get('/hearourpoint', 'SiteController@hearourpoint')->name('hearourpoint');
    Route::get('/acc', 'SiteController@acc')->name('acc');
    Route::get('/partner', 'SiteController@partner')->name('partner');
    Route::get('/invest', 'SiteController@invest')->name('invest');
    Route::get('/apply', 'SiteController@apply')->name('apply');
    Route::get('/about', 'SiteController@about')->name('about');
    Route::get('/support', 'SiteController@support')->name('team');
    Route::get('/testimonial', 'SiteController@testimonial')->name('testimonial');
    Route::get('/blog-list', 'SiteController@bloglist')->name('blog-list');
    Route::get('/blog-grid', 'SiteController@bloggrid')->name('blog-grid');
    Route::get('/blogdetails/{id}/{slug}', 'SiteController@blogdetails');
    Route::get('/blog-search','SiteController@blogsearchpage')->name('blog.search');
    Route::get('/contact', 'SiteController@contact')->name('contact');
    Route::post('/frcontact', 'SiteController@frcontactstore')->name('frcontact.store');
    Route::post('/frpartner', 'SiteController@frpartnerstore')->name('frpartner.store');
    Route::post('/frinvest', 'SiteController@frinveststore')->name('frinvest.store');
    Route::post('/fracc', 'SiteController@fraccstore')->name('fracc.store');
    Route::post('/frsubscribe', 'SiteController@frsubscribestore')->name('frsubscribe.store');
});


Route::group(['prefix'=>'admin','middleware'=>['auth','XSS']],function(){

    //Language
    Route::get('lang/{lang}', 'Admin\LanguageController@switchLang')->name('lang.switch');
    // Dashboard
    Route::resource('dashboard', 'Admin\DashboardController');

    // Profile
    Route::resource('profile', 'Admin\ProfileController');
    Route::get('profile/destroy/{id}','Admin\ProfileController@destroy')->name('profile.destroy');

    // General
    Route::resource('general', 'Admin\GeneralController');
    Route::post('general/destroy','Admin\GeneralController@destroy')->name('general.destroy');
    Route::get('general/destroy/{id}','Admin\GeneralController@destroy')->name('general.destroy');

    // Mainslider
    Route::resource('mainslider', 'Admin\MainSliderController');
    Route::get('mainslider/destroy/{id}','Admin\MainSliderController@destroy')->name('mainslider.destroy');

    // About
    Route::resource('about', 'Admin\AboutController');
    Route::get('about/destroy/{id}','Admin\AboutController@destroy')->name('about.destroy');

    // Counter
    Route::resource('counter', 'Admin\CounterController');
    Route::get('counter/destroy/{id}','Admin\CounterController@destroy')->name('counter.destroy');

    // Service
    Route::resource('service', 'Admin\ServiceController');
    Route::get('service/destroy/{id}','Admin\ServiceController@destroy')->name('service.destroy');

    // Service content
    Route::resource('servicecontent', 'Admin\ServiceContentController');
    Route::get('servicecontent/destroy/{id}','Admin\ServiceContentController@destroy')->name('servicecontent.destroy');

    // Team
    Route::resource('team', 'Admin\TeamController');
    Route::get('team/destroy/{id}','Admin\TeamController@destroy')->name('team.destroy');

    // Team content
    Route::resource('teamcontent', 'Admin\TeamContentController');
    Route::get('teamcontent/destroy/{id}','Admin\TeamContentController@destroy')->name('teamcontent.destroy');

    // Cta
    Route::resource('cta', 'Admin\CtaController');
    Route::get('cta/destroy/{id}','Admin\CtaController@destroy')->name('cta.destroy');

    // Testimonial
    Route::resource('testimonial', 'Admin\TestimonialController');
    Route::get('testimonial/destroy/{id}','Admin\TestimonialController@destroy')->name('testimonial.destroy');

    // Testimonial content
    Route::resource('testimonialcontent', 'Admin\TestimonialContentController');
    Route::get('testimonialcontent/destroy/{id}','Admin\TestimonialContentController@destroy')->name('testimonialcontent.destroy');

    // Video
    Route::resource('video', 'Admin\VideoController');
    Route::get('video/destroy/{id}','Admin\VideoController@destroy')->name('video.destroy');

    // Video content
    Route::resource('videocontent', 'Admin\VideoContentController');
    Route::get('videocontent/destroy/{id}','Admin\VideoContentController@destroy')->name('videocontent.destroy');

    // Blog
    Route::resource('blog', 'Admin\BlogController');
    Route::get('blog/destroy/{id}','Admin\BlogController@destroy')->name('blog.destroy');

    // Blog content
    Route::resource('blogcontent', 'Admin\BlogContentController');
    Route::get('blogcontent/destroy/{id}','Admin\BlogContentController@destroy')->name('blogcontent.destroy');

    // Subscribe
    Route::resource('subscribe', 'Admin\SubscribeController');
    Route::get('subscribe/destroy/{id}','Admin\SubscribeController@destroy')->name('subscribe.destroy');

    // Subscribe Content
    Route::resource('subscribecontent', 'Admin\SubscribeContentController');
    Route::get('subscribecontent/destroy/{id}','Admin\SubscribeContentController@destroy')->name('subscribecontent.destroy');

    // Ecosystempartner
    Route::resource('client', 'Admin\ClientController');
    Route::get('client/destroy/{id}','Admin\ClientController@destroy')->name('client.destroy');

    // Widget1
    Route::resource('widget1', 'Admin\Widget1Controller');
    Route::get('widget1/destroy/{id}','Admin\Widget1Controller@destroy')->name('widget1.destroy');

    // Widget2
    Route::resource('widget2', 'Admin\Widget2Controller');
    Route::get('widget2/destroy/{id}','Admin\Widget2Controller@destroy')->name('widget2.destroy');

    // Widget3
    Route::resource('widget3', 'Admin\Widget3Controller');
    Route::get('widget3/destroy/{id}','Admin\Widget3Controller@destroy')->name('widget3.destroy');

    // Contact
    Route::resource('contact', 'Admin\ContactController');
    Route::get('contact/destroy/{id}','Admin\ContactController@destroy')->name('contact.destroy');

    // Contact Info
    Route::resource('contactinfo', 'Admin\ContactinfoController');
    Route::get('contactinfo/destroy/{id}','Admin\ContactinfoController@destroy')->name('contactinfo.destroy');

    // optimizer
    Route::get('optimizer', function() {
        Artisan::call('cache:clear');
        Artisan::call('route:clear');
        Artisan::call('config:clear');
        Artisan::call('view:clear');
        $notification = array(
            'message' => __('messages.Your Site Optimize Successfully'),
            'alert-type' => 'success'
        );
        return redirect()->back()->with($notification);
    });

});

app/Http/Controllers/Admin/ClientController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use App\Models\Profile;
use App\Models\communitypartner;
use Illuminate\Http\Request;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $client=communitypartner::latest()->get();
        $profile=Profile::first();
        return view('admin.client.client', compact('client','profile'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)

    {
        $validatedData = $request->validate([
            'fcli_link' => 'nullable',
            'fcli_image' => 'required|image|mimes:png,jpeg,jpg',
        ]);

        //communitypartner Style Image

        if ($request->fcli_image) {

            $imageName = time().'2.'.request()->fcli_image->getClientOriginalExtension();
            request()->fcli_image->move('assets/img/client/',$imageName);
            $fcli_image='assets/img/client/'.$imageName;
        }

        $client=new communitypartner;
        $client->dcli_link=$request->fcli_link;
        $client->dcli_image=$fcli_image;
        $client->save();
        $notification = array(
            'message' => 'communitypartner Created Successfully',
            'alert-type' => 'success'
        );
        return redirect()->back()->with($notification);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function show(communitypartner $client)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function edit(communitypartner $client)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)

    {
        $validatedData = $request->validate([
            'fcli_link' => 'nullable',
            'fcli_image' => 'image|mimes:png,jpeg,jpg',
        ]);


        $client=communitypartner::find($id);

        //client Style Icon
        if ($request->hasFile('fcli_image')) {

            $imageName = time().'2.'.request()->fcli_image->getClientOriginalExtension();
            request()->fcli_image->move('assets/img/client/',$imageName);
            $fcli_image='assets/img/client/'.$imageName;

            if (file_exists($client->dcli_image)) {
                unlink($client->dcli_image);
             }
             $client->dcli_image=$fcli_image;

        }


        $client->dcli_link=$request->fcli_link;
        $client->save();
        $notification = array(
            'message' => 'communitypartner Updated Successfully',
            'alert-type' => 'success'
        );
        return redirect()->back()->with($notification);
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $info=communitypartner::find($id);

        if (file_exists($info->dcli_image)) {
            unlink($info->dcli_image);
        }

        communitypartner::destroy($id);
       $notification = array(
            'message' => 'communitypartner Delete Successfully',
            'alert-type' => 'success'
        );
        return back()->with($notification);
    }

}

resources/views/admin/client/client.blade.php
@extends('admin.master')
@section('title')
{{ __('messages.communitypartner') }}
@endsection
@section('admincontent')
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">
                        {{ __('messages.communitypartner Table') }}
                        <button type="button" class="btn btn-primary float-right" data-toggle="modal"
                            data-target="#clientmodal">{{ __('messages.Create communitypartner') }}</button>
                    </h4>
                    <!-- modal start -->
                    <!-- Modal -->
                    <div class="modal fade" id="clientmodal" tabindex="-1" role="dialog" aria-labelledby="modaltitle"
                        aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="modaltitle">{{ __('messages.Create communitypartner') }}</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <!-- Modal Body Contant Start -->
                                    <form action="{{ route('client.store') }}" method="POST"
                                        class="create-client-form-wraper" enctype="multipart/form-data">
                                        @csrf
                                        <div class="form-group">
                                            <label for="fcli_link">{{ __('messages.communitypartner Link') }}</label>
                                            <input id="fcli_link" type="text" name="fcli_link" class="form-control"
                                                placeholder="{{ __('messages.Your Link Here') }}">
                                        </div>

                                        <div class="form-group">
                                            <label for="fcli_image">{{ __('messages.Upload Image') }}</label>
                                            <input id="fcli_image" type="file" name="fcli_image" class="form-control"
                                                required>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="submit" class="btn btn-secondary"
                                                data-dismiss="modal">{{ __('messages.Close') }}</button>
                                            <button type="submit" class="btn btn-primary">{{ __('messages.Save') }}</button>
                                        </div>

                                    </form>

                                    <!-- Modal Body Contant End -->
                                </div>

                            </div>
                        </div>
                    </div>
                    <!-- modal end -->
                    <!-- Error Start -->
                    @if($errors->any())
                        <ul class="alert alert-danger alert-dismissible fade show mt-5">
                            @foreach($errors->all() as $error)
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    @endif
                    <!-- Error End -->
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered zero-configuration">
                            <thead>
                                <tr>
                                    <th>{{ __('messages.No') }}</th>
                                    <th>{{ __('messages.Link') }}</th>
                                    <th>{{ __('messages.Image') }}</th>
                                    <th scope="col">{{ __('messages.Action') }}</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach($client as $key => $item)

                                    <tr>
                                        <td>{{ $key+1 }}</td>
                                        <td>{{ $item->dcli_link }}</td>
                                        <td><img src="{{ asset($item->dcli_image) }}" alt="img-alt" /></td>
                                        <td>
                                            <span>

                                                <button type="button" class="btn mb-1 btn-primary modal-title"
                                                    data-toggle="modal" data-target="#ClientEditModal{{ $key }}">
                                                    <i class="fa fa-pencil color-muted m-r-5"></i>
                                                </button>


                                                <a href="{{ route('client.destroy',$item->id) }}"
                                                    class="btn mb-1 btn-danger"><i
                                                        class="fa fa-close color-danger"></i></a>

                                            </span>
                                        </td>
                                    </tr>

                                    <!-- Hero Edit Modal -->
                                    <div class="modal fade" id="ClientEditModal{{ $key }}" tabindex="-1" role="dialog"
                                        aria-labelledby="editmodaltitle" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="editmodaltitle">{{ __('messages.Edit Slider') }}</h5>
                                                    <button type="button" class="close" data-dismiss="modal"
                                                        aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <!-- Modal Body Contant Start -->
                                                    <form class="create-slider-form-wraper" method="POST"
                                                        action="{{ route('client.update',$item->id) }}"
                                                        enctype="multipart/form-data">
                                                        @csrf
                                                        @method('PUT')

                                                        <div class="form-group">
                                                            <label for="fcli_link">{{ __('messages.communitypartner Link') }}</label>
                                                            <input id="fcli_link" type="text" name="fcli_link"
                                                                class="form-control"
                                                                value="{{ $item->dcli_link }}">
                                                        </div>

                                                        <div class="form-group">
                                                            <label for="fcli_image">Upload Image</label>
                                                            <input id="fcli_image" type="file" name="fcli_image"
                                                                class="form-control" value="{{ $item->dcli_image }}">
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="submit" class="btn btn-secondary"
                                                                data-dismiss="modal">{{ __('messages.Close') }}</button>
                                                            <button type="submit" class="btn btn-primary">{{ __('messages.Save') }}</button>
                                                        </div>

                                                    </form>
                                                    <!-- Modal Body Contant End -->
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Hero Edit Modal -->

                                @endforeach

                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>{{ __('messages.No') }}</th>
                                    <th>{{ __('messages.Link') }}</th>
                                    <th>{{ __('messages.Image') }}</th>
                                    <th scope="col">{{ __('messages.Action') }}</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
@endsection