routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'login' => true,
    'register' => true,
    'reset' => false,
    ]);

    Route::middleware(['XSS'])->group(function () {

    //Installation Part

    Route::get('/install','Installer\InstallerController@install')->name('install')->middleware('installer');

    Route::get('/install/info','Installer\InstallerController@info')->name('install.info');
    Route::get('/install/check/{param}','Installer\InstallerController@check')->name('install.check');
    Route::get('pre/install','Installer\InstallerController@preinstall')->name('preinstall');
    Route::post('/install/store','Installer\InstallerController@send');

    //Frontend Part

    Route::get('/', 'SiteController@index')->name('index');
    Route::get('/hearourpoint', 'SiteController@hearourpoint')->name('hearourpoint');
    Route::get('/acc', 'SiteController@acc')->name('acc');
    Route::get('/partner', 'SiteController@partner')->name('partner');
    Route::get('/invest', 'SiteController@invest')->name('invest');
    Route::get('/apply', 'SiteController@apply')->name('apply');
    Route::get('/about', 'SiteController@about')->name('about');
    Route::get('/support', 'SiteController@support')->name('team');
    Route::get('/testimonial', 'SiteController@testimonial')->name('testimonial');
    Route::get('/blog-list', 'SiteController@bloglist')->name('blog-list');
    Route::get('/blog-grid', 'SiteController@bloggrid')->name('blog-grid');
    Route::get('/blogdetails/{id}/{slug}', 'SiteController@blogdetails');
    Route::get('/blog-search','SiteController@blogsearchpage')->name('blog.search');
    Route::get('/contact', 'SiteController@contact')->name('contact');
    Route::post('/frcontact', 'SiteController@frcontactstore')->name('frcontact.store');
    Route::post('/frpartner', 'SiteController@frpartnerstore')->name('frpartner.store');
    Route::post('/frinvest', 'SiteController@frinveststore')->name('frinvest.store');
    Route::post('/fracc', 'SiteController@fraccstore')->name('fracc.store');
    Route::post('/frsubscribe', 'SiteController@frsubscribestore')->name('frsubscribe.store');
});


Route::group(['prefix'=>'admin','middleware'=>['auth','XSS']],function(){

    //Language
    Route::get('lang/{lang}', 'Admin\LanguageController@switchLang')->name('lang.switch');
    // Dashboard
    Route::resource('dashboard', 'Admin\DashboardController');

    // Profile
    Route::resource('profile', 'Admin\ProfileController');
    Route::get('profile/destroy/{id}','Admin\ProfileController@destroy')->name('profile.destroy');

    // General
    Route::resource('general', 'Admin\GeneralController');
    Route::post('general/destroy','Admin\GeneralController@destroy')->name('general.destroy');
    Route::get('general/destroy/{id}','Admin\GeneralController@destroy')->name('general.destroy');

    // Mainslider
    Route::resource('mainslider', 'Admin\MainSliderController');
    Route::get('mainslider/destroy/{id}','Admin\MainSliderController@destroy')->name('mainslider.destroy');

    // About
    Route::resource('about', 'Admin\AboutController');
    Route::get('about/destroy/{id}','Admin\AboutController@destroy')->name('about.destroy');

    // Counter
    Route::resource('counter', 'Admin\CounterController');
    Route::get('counter/destroy/{id}','Admin\CounterController@destroy')->name('counter.destroy');

    // Service
    Route::resource('service', 'Admin\ServiceController');
    Route::get('service/destroy/{id}','Admin\ServiceController@destroy')->name('service.destroy');

    // Service content
    Route::resource('servicecontent', 'Admin\ServiceContentController');
    Route::get('servicecontent/destroy/{id}','Admin\ServiceContentController@destroy')->name('servicecontent.destroy');

    // Team
    Route::resource('team', 'Admin\TeamController');
    Route::get('team/destroy/{id}','Admin\TeamController@destroy')->name('team.destroy');

    // Team content
    Route::resource('teamcontent', 'Admin\TeamContentController');
    Route::get('teamcontent/destroy/{id}','Admin\TeamContentController@destroy')->name('teamcontent.destroy');

    // Cta
    Route::resource('cta', 'Admin\CtaController');
    Route::get('cta/destroy/{id}','Admin\CtaController@destroy')->name('cta.destroy');

    // Testimonial
    Route::resource('testimonial', 'Admin\TestimonialController');
    Route::get('testimonial/destroy/{id}','Admin\TestimonialController@destroy')->name('testimonial.destroy');

    // Testimonial content
    Route::resource('testimonialcontent', 'Admin\TestimonialContentController');
    Route::get('testimonialcontent/destroy/{id}','Admin\TestimonialContentController@destroy')->name('testimonialcontent.destroy');

    // Video
    Route::resource('video', 'Admin\VideoController');
    Route::get('video/destroy/{id}','Admin\VideoController@destroy')->name('video.destroy');

    // Video content
    Route::resource('videocontent', 'Admin\VideoContentController');
    Route::get('videocontent/destroy/{id}','Admin\VideoContentController@destroy')->name('videocontent.destroy');

    // Blog
    Route::resource('blog', 'Admin\BlogController');
    Route::get('blog/destroy/{id}','Admin\BlogController@destroy')->name('blog.destroy');

    // Blog content
    Route::resource('blogcontent', 'Admin\BlogContentController');
    Route::get('blogcontent/destroy/{id}','Admin\BlogContentController@destroy')->name('blogcontent.destroy');

    // Subscribe
    Route::resource('subscribe', 'Admin\SubscribeController');
    Route::get('subscribe/destroy/{id}','Admin\SubscribeController@destroy')->name('subscribe.destroy');

    // Subscribe Content
    Route::resource('subscribecontent', 'Admin\SubscribeContentController');
    Route::get('subscribecontent/destroy/{id}','Admin\SubscribeContentController@destroy')->name('subscribecontent.destroy');

    // Ecosystempartner
    Route::resource('client', 'Admin\ClientController');
    Route::get('client/destroy/{id}','Admin\ClientController@destroy')->name('client.destroy');

    // Widget1
    Route::resource('widget1', 'Admin\Widget1Controller');
    Route::get('widget1/destroy/{id}','Admin\Widget1Controller@destroy')->name('widget1.destroy');

    // Widget2
    Route::resource('widget2', 'Admin\Widget2Controller');
    Route::get('widget2/destroy/{id}','Admin\Widget2Controller@destroy')->name('widget2.destroy');

    // Widget3
    Route::resource('widget3', 'Admin\Widget3Controller');
    Route::get('widget3/destroy/{id}','Admin\Widget3Controller@destroy')->name('widget3.destroy');

    // Contact
    Route::resource('contact', 'Admin\ContactController');
    Route::get('contact/destroy/{id}','Admin\ContactController@destroy')->name('contact.destroy');

    // Contact Info
    Route::resource('contactinfo', 'Admin\ContactinfoController');
    Route::get('contactinfo/destroy/{id}','Admin\ContactinfoController@destroy')->name('contactinfo.destroy');

    // optimizer
    Route::get('optimizer', function() {
        Artisan::call('cache:clear');
        Artisan::call('route:clear');
        Artisan::call('config:clear');
        Artisan::call('view:clear');
        $notification = array(
            'message' => __('messages.Your Site Optimize Successfully'),
            'alert-type' => 'success'
        );
        return redirect()->back()->with($notification);
    });

});

resources/views/admin/admin_footer_copyright.blade.php
<div class="footer">
    <div class="copyright">
        @if(App\Models\General::count() > 0)
            @foreach(App\Models\General::latest()->get() as $item)
                @if(!empty( $item->dfooter_copyright ))
                    {!! $item->dfooter_copyright !!}
                @else

                    <p>{{ __('messages.Copyright') }} &copy; <a target="_blank" href="https://themeforest.net/user/theme_group">{{ __('messages.theme_group') }}</a></p>
                @endif
            @endforeach
        @else
        <p>{{ __('messages.Copyright') }} &copy; <a target="_blank" href="https://themeforest.net/user/theme_group">{{ __('messages.theme_group') }}</a></p>
        @endif
    </div>
</div>
</div>

resources/views/admin/admin_footer_scripts.blade.php
<script src="{{ asset('assets/admin/plugins/common/common.min.js') }}"></script>
<script src="{{ asset('assets/admin/js/custom.min.js') }}"></script>
<script src="{{ asset('assets/admin/js/settings.js') }}"></script>
<script src="{{ asset('assets/admin/js/gleek.js') }}"></script>
<script src="{{ asset('assets/admin/js/styleSwitcher.js') }}"></script>
<script src="{{ asset('assets/admin/js/summernote.min.js') }}"></script>
<script src="{{ asset('assets/admin/js/summernote-init.js') }}"></script>
{{-- <script src="{{ asset('assets/admin/js/toastr.min.js') }}"></script>
--}}
<script src="{{ asset('assets/admin/js/bootstrap-tagsinput.js') }}"></script>
<script src="{{ asset('assets/admin/plugins/tables/js/jquery.dataTables.min.js') }}">
</script>
<script
    src="{{ asset('assets/admin/plugins/tables/js/datatable/dataTables.bootstrap4.min.js') }}">
</script>
<script
    src="{{ asset('assets/admin/plugins/tables/js/datatable-init/datatable-basic.min.js') }}">
</script>

<script src="{{ asset('assets/admin/js/sweetalert.min.js') }}"></script>

@if(Session::has('message'))
    <script>
        (function ($) {
            "use strict";

            var type = "{{ Session::get('alert-type', 'info') }}";
            switch (type) {
                case 'info':

                    swal("Good job!", "{{ Session::get('message') }}", "info", {
                        button: "OK",
                    });

                    break;

                case 'success':
                    swal("Good job!", "{{ Session::get('message') }}", "success", {
                        button: "OK",
                    });
                    break;

                case 'warning':
                    swal("Good job!", "{{ Session::get('message') }}", "warning", {
                        button: "OK",
                    });
                    break;

                case 'error':
                    swal("Good job!", "{{ Session::get('message') }}", "error", {
                        button: "OK",
                    });
                    break;
            }


        })(jQuery);

    </script>

@endif

<script>
    $('.btn-danger').on('click', function (event) {
        event.preventDefault();
        const url = $(this).attr('href');
        swal({
            title: 'Are you sure?',
            text: 'This record and it`s details will be permanantly deleted!',
            icon: 'error',
            buttons: ["Cancel", "Yes!"],
        }).then(function (value) {
            if (value) {
                window.location.href = url;
            } else {
                swal({
                    title: 'Hurrah!',
                    text: 'Your file is safe Now!',
                    icon: 'success',
                    button: "OK",
                })
            }
        });
    });

</script>
</body>

</html>

resources/views/admin/admin_header_after_content.blade.php
<!--
Main wrapper start
 *-->
<div id="main-wrapper">

    <!--
Nav header start
 *-->
    <div class="nav-header">
        <div class="brand-logo">
            <a href="{{ route('dashboard.index') }}">
                <b class="logo-abbr">
                    @if(App\Models\General::count() > 0)
                        @foreach(App\Models\General::latest()->get() as $item)
                            @if(!empty( $item->dfavicon_icon ))

                                <img src="{{ asset( $item->dfavicon_icon ) }}" alt="img-alt">
                            @else

                                <img src="{{ asset('assets/img/logo-compact.png') }}"
                                    alt="img-alt">
                            @endif
                        @endforeach
                    @else
                        <img src="{{ asset('assets/img/logo-compact.png') }}" alt="img-alt">
                    @endif
                </b>
                <span class="brand-title">

                    @if(App\Models\General::count() > 0)
                        @foreach(App\Models\General::latest()->get() as $item)

                            @if(!empty( $item->dtop_logo ))

                                <img src="{{ asset( $item->dtop_logo ) }}" alt="img-alt">
                            @else

                                <img src="{{ asset('assets/img/logo-1.png') }}" alt="img-alt">
                            @endif
                        @endforeach
                    @else
                        <img src="{{ asset('assets/img/logo-1.png') }}" alt="img-alt">
                    @endif

                </span>
            </a>
        </div>
    </div>
    <!--
Nav header end
 *-->

    <!--
Header start
 *-->
    <div class="header">
        <div class="header-content clearfix">

            <div class="nav-control">
                <div class="hamburger">
                    <span class="toggle-icon"><i class="icon-menu"></i></span>
                </div>
            </div>
            <div class="header-left"></div>
            <div class="header-right">
                <ul class="clearfix">
                    <li class="icons dropdown d-none d-md-flex">
                        <a class="mb-10" href="{{ url('/') }}" target="_blank" rel="noopener noreferrer">{{ __('messages.View Site') }} <i class="fa fa-external-link"></i> </a>
                    </li>


                    <li class="icons dropdown d-none d-md-flex">
                        <a href="javascript:void(0)" class="log-user"  data-toggle="dropdown">
                            {{ Config::get('languages')[App::getLocale()]['display'] }}  <i class="fa fa-angle-down f-s-14" aria-hidden="true"></i>
                        </a>
                        <div class="drop-down dropdown-language animated fadeIn  dropdown-menu">
                            <div class="dropdown-content-body">
                                <ul>
                                    @foreach (Config::get('languages') as $lang => $language)
                                    @if ($lang != App::getLocale())
                                           <li><a href="{{ route('lang.switch', $lang) }}">{{$language['display']}}</a></li>
                                    @endif
                                @endforeach
                                </ul>
                            </div>
                        </div>
                    </li>

                    <li class="icons dropdown">
                        <div class="user-img c-pointer position-relative" data-toggle="dropdown">
                            <span class="activity active"></span>


                            @if(!empty($profile->dpr_image))

                                <img src="{{ asset($profile->dpr_image) }}" alt="img-alt">

                            @else
                                <div class="admin-profile-style-static">
                                    {{ __('messages.AM') }}
                                </div>
                            @endif


                        </div>
                        <div class="drop-down dropdown-profile animated fadeIn dropdown-menu">
                            <div class="dropdown-content-body">
                                <ul>
                                    <li>
                                        <a href="{{ route('profile.index') }}"><i
                                                class="icon-user"></i>
                                            <span>{{ __('messages.Profile') }}</span></a>
                                    </li>
                                    <hr class="my-2">
                                    <li><a href="{{ route('logout') }}" onclick="event.preventDefault();
                                                      document.getElementById('logout-form').submit();"><i
                                                class="icon-key"></i>{{ __('messages.Logout') }}</a>


                                        <form id="logout-form" action="{{ route('logout') }}"
                                            method="POST" class="d-none">
                                            @csrf
                                        </form>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>

resources/views/admin/admin_header_style.blade.php
<!DOCTYPE html>
<html class="h-100" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    @if(App\Models\General::count() > 0)
        @foreach(App\Models\General::latest()->get() as $item)

            @if(!empty( $item->dsite_title ))

                <title>{{ $item->dsite_title }} </title>
            @else

                <title>{{ __('messages.Merox - Business Management System') }}</title>
            @endif
        @endforeach
    @else
        <title>{{ __('messages.Merox - Business Management System') }}</title>
    @endif

    <!-- Favicon icon -->

    @if(App\Models\General::count() > 0)
        @foreach(App\Models\General::latest()->get() as $item)
            @if(!empty( $item->dfavicon_icon ))

                <link rel="icon" type="image/png" sizes="16x16" href="{{ asset( $item->dfavicon_icon ) }}">
            @else

                <link rel="icon" type="image/png" sizes="16x16"
                    href="{{ asset('assets/img/favicon.png') }}">
            @endif
        @endforeach
    @else
        <link rel="icon" type="image/png" sizes="16x16"
            href="{{ asset('assets/img/favicon.png') }}">
    @endif

    <!-- Custom Stylesheet -->
    <link
        href="{{ asset('assets/admin/icons/simple-line-icons/css/simple-line-icons.css') }}"
        rel="stylesheet">
    <link href="{{ asset('assets/admin/icons/font-awesome/css/font-awesome.min.css') }}"
        rel="stylesheet">
    <link href="{{ asset('assets/admin/icons/themify-icons/themify-icons.css') }}"
        rel="stylesheet">
    <link href="{{ asset('assets/admin/icons/linea-icons/linea.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/admin/css/style.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/admin/css/metisMenu.min.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/admin/css/summernote.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/admin/css/bootstrap-tagsinput.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/admin/css/adminmaster.css') }}" rel="stylesheet">
</head>

<body>


    <!--*******************
Preloader start
********************-->
    <div id="preloader">
        <div class="loader">
            <svg class="circular" viewBox="25 25 50 50">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10" />
            </svg>
        </div>
    </div>
    <!--*******************
Preloader end
********************-->

resources/views/admin/admin_nave.blade.php
<div class="nk-sidebar">
    <div class="nk-nav-scroll">
        <ul class="metismenu" id="menu">

            <li>
                <a href="{{ route('dashboard.index') }}" aria-expanded="false">
                    <i class="fa fa-dashboard menu-icon"></i><span class="nav-text">{{ __('messages.Dashboard') }}</span>
                </a>
            </li>

            <li>
                <a href="{{ route('general.index') }}" aria-expanded="false">
                    <i class="icon-home menu-icon"></i><span class="nav-text">{{ __('messages.General Settings') }}</span>
                </a>
            </li>

            <li>
                <a href="{{ route('mainslider.index') }}" aria-expanded="false">
                    <i class="fa fa-sliders menu-icon"></i><span class="nav-text">{{ __('messages.Main Slider') }}</span>
                </a>
            </li>

            <li>
                <a href="{{ route('about.index') }}" aria-expanded="false">
                    <i class="fa fa-user-circle-o menu-icon"></i><span class="nav-text">{{ __('messages.About') }}</span>
                </a>
            </li>

            <li>
                <a href="{{ route('counter.index') }}" aria-expanded="false">
                    <i class="icon-hourglass menu-icon"></i><span class="nav-text">{{ __('messages.Counter') }}</span>
                </a>
            </li>

            <li>
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="fa fa-sitemap menu-icon"></i><span class="nav-text">{{ __('messages.Services') }}</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="{{ route('service.index') }}">{{ __('messages.Create') }}</a></li>
                    <li><a href="{{ route('servicecontent.index') }}">{{ __('messages.Content') }}</a></li>

                </ul>
            </li>

            <li>
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="icon-people menu-icon"></i><span class="nav-text">{{ __('messages.Team') }}</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="{{ route('team.index') }}">{{ __('messages.Create') }}</a></li>
                    <li><a href="{{ route('teamcontent.index') }}">{{ __('messages.Content') }}</a></li>

                </ul>
            </li>

            <li>
                <a href="{{ route('cta.index') }}" aria-expanded="false">
                    <i class="icon-home menu-icon"></i><span class="nav-text">{{ __('messages.Cta') }}</span>
                </a>
            </li>

            <li>
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="icon-grid menu-icon"></i><span class="nav-text">{{ __('messages.Testimonial') }}</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="{{ route('testimonial.index') }}">{{ __('messages.Create') }}</a></li>
                    <li><a href="{{ route('testimonialcontent.index') }}">{{ __('messages.Content') }}</a></li>

                </ul>
            </li>

            <li>
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="icon-control-play menu-icon"></i><span class="nav-text">{{ __('messages.Video') }}</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="{{ route('video.index') }}">{{ __('messages.Create') }}</a></li>
                    <li><a href="{{ route('videocontent.index') }}">{{ __('messages.Content') }}</a></li>

                </ul>
            </li>


            <li>
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="icon-grid menu-icon"></i><span class="nav-text">{{ __('messages.Blog') }}</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="{{ route('blog.index') }}">{{ __('messages.Create') }}</a></li>
                    <li><a href="{{ route('blogcontent.index') }}">{{ __('messages.Content') }}</a></li>

                </ul>
            </li>

            <li>
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="icon-grid menu-icon"></i><span class="nav-text">{{ __('messages.Subscribe') }}</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="{{ route('subscribe.index') }}">{{ __('messages.E-mail List') }}</a></li>
                    <li><a href="{{ route('subscribecontent.index') }}">{{ __('messages.Content') }}</a></li>
                </ul>
            </li>

            <li>
                <a href="{{ route('client.index') }}" aria-expanded="false">
                    <i class="icon-grid menu-icon"></i><span class="nav-text">{{ __('messages.communitypartner') }}</span>
                </a>
            </li>

            <li>
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="icon-grid menu-icon"></i><span class="nav-text">{{ __('messages.Footer') }}</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="{{ route('widget1.index') }}">{{ __('messages.About') }}</a></li>
                    <li><a href="{{ route('widget2.index') }}">{{ __('messages.Quick Link') }}</a></li>
                    <li><a href="{{ route('widget3.index') }}">{{ __('messages.Contact Info') }}</a></li>

                </ul>
            </li>


            <li>
                <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                    <i class="icon-grid menu-icon"></i><span class="nav-text">{{ __('messages.Contact') }}</span>
                </a>
                <ul aria-expanded="false">
                    <li><a href="{{ route('contact.index') }}">{{ __('messages.Contact') }}</a></li>
                    <li><a href="{{ route('contactinfo.index') }}">{{ __('messages.Contact Info') }}</a></li>

                </ul>
            </li>

            <li>
                <a href="{{ url('admin/optimizer') }}" aria-expanded="false">
                    <i class="icon-grid menu-icon"></i><span class="nav-text">{{ __('messages.Optimizer') }}</span>
                </a>
            </li>
            <!-- menu end-->

        </ul>
    </div>
</div>

resources/views/admin/dashboard.blade.php
@extends('admin.master')
@section('title')
{{ __('messages.Dashboard') }}
@endsection
@section('admincontent')
<!-- Content body start -->
<div class="container-fluid mt-3">
    <div class="row">
        <div class="col-lg-3 col-sm-6">
            <div class="card gradient-1">
                <div class="card-body">
                    <h3 class="card-title text-white">{{ __('messages.Total Subscribers') }}</h3>
                    <div class="d-inline-block">
                        <h2 class="text-white">{{ App\Models\Subscribe::count() }}</h2>
                    </div>
                    <span class="float-right display-5 opacity-5"><i class="fa fa-users"></i></span>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6">
            <div class="card gradient-2">
                <div class="card-body">
                    <h3 class="card-title text-white">{{ __('messages.Total Service') }}</h3>
                    <div class="d-inline-block">
                        <h2 class="text-white">{{ App\Models\Service::count() }}</h2>
                    </div>
                    <span class="float-right display-5 opacity-5"><i class="fa fa-sliders"></i></span>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-sm-6">
            <div class="card gradient-3">
                <div class="card-body">
                    <h3 class="card-title text-white">{{ __('messages.Total Contact') }}</h3>
                    <div class="d-inline-block">
                        <h2 class="text-white">{{ App\Models\Contact::count() }}</h2>
                    </div>
                    <span class="float-right display-5 opacity-5"><i class="fa fa-users"></i></span>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6">
            <div class="card gradient-4">
                <div class="card-body">
                    <h3 class="card-title text-white">{{ __('messages.Total Blog') }}</h3>
                    <div class="d-inline-block">
                        <h2 class="text-white">{{ App\Models\Blog::count() }}</h2>
                    </div>
                    <span class="float-right display-5 opacity-5"><i class="fa fa-bold"></i></span>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<!-- Content body end -->
@endsection

resources/views/admin/master.blade.php
@includeif('admin.admin_header_style')
    @includeif('admin.admin_header_after_content')
        @includeif('admin.admin_nave')
            <div class="content-body">

                <div class="row page-titles mx-0">
                    <div class="col p-md-0">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a
                                    href="{{ route('dashboard.index') }}">{{ __('messages.Dashboard') }}</a></li>
                            <li class="breadcrumb-item active">@yield('title')</li>
                        </ol>
                    </div>
                </div>
                <!-- row -->
                @yield('admincontent')
            </div>
            @includeif('admin.admin_footer_copyright')
                @includeif('admin.admin_footer_scripts')