routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'login' => true,
    'register' => true,
    'reset' => false,
    ]);

    Route::middleware(['XSS'])->group(function () {

    //Installation Part

    Route::get('/install','Installer\InstallerController@install')->name('install')->middleware('installer');

    Route::get('/install/info','Installer\InstallerController@info')->name('install.info');
    Route::get('/install/check/{param}','Installer\InstallerController@check')->name('install.check');
    Route::get('pre/install','Installer\InstallerController@preinstall')->name('preinstall');
    Route::post('/install/store','Installer\InstallerController@send');

    //Frontend Part

    Route::get('/', 'SiteController@index')->name('index');
    Route::get('/hearourpoint', 'SiteController@hearourpoint')->name('hearourpoint');
    Route::get('/acc', 'SiteController@acc')->name('acc');
    Route::get('/partner', 'SiteController@partner')->name('partner');
    Route::get('/invest', 'SiteController@invest')->name('invest');
    Route::get('/apply', 'SiteController@apply')->name('apply');
    Route::get('/about', 'SiteController@about')->name('about');
    Route::get('/support', 'SiteController@support')->name('team');
    Route::get('/testimonial', 'SiteController@testimonial')->name('testimonial');
    Route::get('/blog-list', 'SiteController@bloglist')->name('blog-list');
    Route::get('/blog-grid', 'SiteController@bloggrid')->name('blog-grid');
    Route::get('/blogdetails/{id}/{slug}', 'SiteController@blogdetails');
    Route::get('/blog-search','SiteController@blogsearchpage')->name('blog.search');
    Route::get('/contact', 'SiteController@contact')->name('contact');
    Route::post('/frcontact', 'SiteController@frcontactstore')->name('frcontact.store');
    Route::post('/frpartner', 'SiteController@frpartnerstore')->name('frpartner.store');
    Route::post('/frinvest', 'SiteController@frinveststore')->name('frinvest.store');
    Route::post('/fracc', 'SiteController@fraccstore')->name('fracc.store');
    Route::post('/frsubscribe', 'SiteController@frsubscribestore')->name('frsubscribe.store');
});


Route::group(['prefix'=>'admin','middleware'=>['auth','XSS']],function(){

    //Language
    Route::get('lang/{lang}', 'Admin\LanguageController@switchLang')->name('lang.switch');
    // Dashboard
    Route::resource('dashboard', 'Admin\DashboardController');

    // Profile
    Route::resource('profile', 'Admin\ProfileController');
    Route::get('profile/destroy/{id}','Admin\ProfileController@destroy')->name('profile.destroy');

    // General
    Route::resource('general', 'Admin\GeneralController');
    Route::post('general/destroy','Admin\GeneralController@destroy')->name('general.destroy');
    Route::get('general/destroy/{id}','Admin\GeneralController@destroy')->name('general.destroy');

    // Mainslider
    Route::resource('mainslider', 'Admin\MainSliderController');
    Route::get('mainslider/destroy/{id}','Admin\MainSliderController@destroy')->name('mainslider.destroy');

    // About
    Route::resource('about', 'Admin\AboutController');
    Route::get('about/destroy/{id}','Admin\AboutController@destroy')->name('about.destroy');

    // Counter
    Route::resource('counter', 'Admin\CounterController');
    Route::get('counter/destroy/{id}','Admin\CounterController@destroy')->name('counter.destroy');

    // Service
    Route::resource('service', 'Admin\ServiceController');
    Route::get('service/destroy/{id}','Admin\ServiceController@destroy')->name('service.destroy');

    // Service content
    Route::resource('servicecontent', 'Admin\ServiceContentController');
    Route::get('servicecontent/destroy/{id}','Admin\ServiceContentController@destroy')->name('servicecontent.destroy');

    // Team
    Route::resource('team', 'Admin\TeamController');
    Route::get('team/destroy/{id}','Admin\TeamController@destroy')->name('team.destroy');

    // Team content
    Route::resource('teamcontent', 'Admin\TeamContentController');
    Route::get('teamcontent/destroy/{id}','Admin\TeamContentController@destroy')->name('teamcontent.destroy');

    // Cta
    Route::resource('cta', 'Admin\CtaController');
    Route::get('cta/destroy/{id}','Admin\CtaController@destroy')->name('cta.destroy');

    // Testimonial
    Route::resource('testimonial', 'Admin\TestimonialController');
    Route::get('testimonial/destroy/{id}','Admin\TestimonialController@destroy')->name('testimonial.destroy');

    // Testimonial content
    Route::resource('testimonialcontent', 'Admin\TestimonialContentController');
    Route::get('testimonialcontent/destroy/{id}','Admin\TestimonialContentController@destroy')->name('testimonialcontent.destroy');

    // Video
    Route::resource('video', 'Admin\VideoController');
    Route::get('video/destroy/{id}','Admin\VideoController@destroy')->name('video.destroy');

    // Video content
    Route::resource('videocontent', 'Admin\VideoContentController');
    Route::get('videocontent/destroy/{id}','Admin\VideoContentController@destroy')->name('videocontent.destroy');

    // Blog
    Route::resource('blog', 'Admin\BlogController');
    Route::get('blog/destroy/{id}','Admin\BlogController@destroy')->name('blog.destroy');

    // Blog content
    Route::resource('blogcontent', 'Admin\BlogContentController');
    Route::get('blogcontent/destroy/{id}','Admin\BlogContentController@destroy')->name('blogcontent.destroy');

    // Subscribe
    Route::resource('subscribe', 'Admin\SubscribeController');
    Route::get('subscribe/destroy/{id}','Admin\SubscribeController@destroy')->name('subscribe.destroy');

    // Subscribe Content
    Route::resource('subscribecontent', 'Admin\SubscribeContentController');
    Route::get('subscribecontent/destroy/{id}','Admin\SubscribeContentController@destroy')->name('subscribecontent.destroy');

    // Ecosystempartner
    Route::resource('client', 'Admin\ClientController');
    Route::get('client/destroy/{id}','Admin\ClientController@destroy')->name('client.destroy');

    // Widget1
    Route::resource('widget1', 'Admin\Widget1Controller');
    Route::get('widget1/destroy/{id}','Admin\Widget1Controller@destroy')->name('widget1.destroy');

    // Widget2
    Route::resource('widget2', 'Admin\Widget2Controller');
    Route::get('widget2/destroy/{id}','Admin\Widget2Controller@destroy')->name('widget2.destroy');

    // Widget3
    Route::resource('widget3', 'Admin\Widget3Controller');
    Route::get('widget3/destroy/{id}','Admin\Widget3Controller@destroy')->name('widget3.destroy');

    // Contact
    Route::resource('contact', 'Admin\ContactController');
    Route::get('contact/destroy/{id}','Admin\ContactController@destroy')->name('contact.destroy');

    // Contact Info
    Route::resource('contactinfo', 'Admin\ContactinfoController');
    Route::get('contactinfo/destroy/{id}','Admin\ContactinfoController@destroy')->name('contactinfo.destroy');

    // optimizer
    Route::get('optimizer', function() {
        Artisan::call('cache:clear');
        Artisan::call('route:clear');
        Artisan::call('config:clear');
        Artisan::call('view:clear');
        $notification = array(
            'message' => __('messages.Your Site Optimize Successfully'),
            'alert-type' => 'success'
        );
        return redirect()->back()->with($notification);
    });

});

app/Models/Cta.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Cta extends Model
{
    protected $table="ctas";
}

app/Http/Controllers/Admin/CtaController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use App\Models\Cta;
use App\Models\Profile;
use Illuminate\Http\Request;

class CtaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $cta=Cta::first();
        $profile=Profile::first();
        return view('admin.cta.cta', compact('cta','profile'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)

    {
        $validatedData = $request->validate([

            'fcta_big_image' =>'required|image|mimes:png,jpeg,jpg',
            'fcta_title' =>'required',
            'fcta_title_2' =>'nullable',
            'fcta_btn' =>'nullable',
            'fcta_url' =>'nullable',
        ]);


        //Cta Big Image

        if ($request->fcta_big_image) {

            $imageName = time().'1.'.request()->fcta_big_image->getClientOriginalExtension();
            request()->fcta_big_image->move('assets/img/cta/',$imageName);
            $fcta_big_image='assets/img/cta/'.$imageName;
        }

        $cta=new Cta();
        $cta->dcta_title=$request->fcta_title;
        $cta->dcta_title_2=$request->fcta_title_2;
        $cta->dcta_btn=$request->fcta_btn;
        $cta->dcta_url=$request->fcta_url;
        $cta->dcta_big_image=$fcta_big_image;
        $cta->save();
        $notification = array(
            'message' => 'Cta Create Successfully',
            'alert-type' => 'success'
        );
        return redirect()->back()->with($notification);
    }


    /**
     * Display the specified resource.
     *
     * @param  \App\Cta  $cta
     * @return \Illuminate\Http\Response
     */
    public function show(Cta $cta)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Cta  $cta
     * @return \Illuminate\Http\Response
     */
    public function edit(Cta $cta)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Cta  $cta
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)


    {
        $validatedData = $request->validate([
            'fcta_big_image' =>'image|mimes:png,jpeg,jpg',
            'fcta_title' =>'required',
            'fcta_title_2' =>'nullable',
            'fcta_btn' =>'nullable',
            'fcta_url' =>'nullable',
        ]);

        $cta=Cta::find($id);


        //Cta Big Image

        if ($request->hasFile('fcta_big_image')) {

            $imageName = time().'1.'.request()->fcta_big_image->getClientOriginalExtension();
            request()->fcta_big_image->move('assets/img/cta/',$imageName);
            $fcta_big_image='assets/img/cta/'.$imageName;

            if (file_exists($cta->dcta_big_image)) {
                unlink($cta->dcta_big_image);
                }
                $cta->dcta_big_image=$fcta_big_image;
        }

        $cta->dcta_title=$request->fcta_title;
        $cta->dcta_title_2=$request->fcta_title_2;
        $cta->dcta_btn=$request->fcta_btn;
        $cta->dcta_url=$request->fcta_url;
        $cta->save();
        $notification = array(
            'message' => 'Updated Successfully',
            'alert-type' => 'success'
        );
        return redirect()->back()->with($notification);
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Cta  $cta
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cta=Cta::find($id);
        if (file_exists($cta->dcta_big_image)) {
            unlink($cta->dcta_big_image);
        }

        Cta::destroy($id);
       $notification = array(
            'message' => 'Content Delete Successfully',
            'alert-type' => 'success'
        );
        return back()->with($notification);

    }
}

resources/views/admin/cta/cta.blade.php
@extends('admin.master')
@section('title')
{{ __('messages.Cta') }}
@endsection
@section('admincontent')

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">{{ __('messages.Cta Section') }}</h4>

                    <!-- Error Start -->
                    @if($errors->any())
                        <ul class="alert alert-danger alert-dismissible fade show mt-5">
                            @foreach($errors->all() as $error)
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    @endif
                    <!-- Error End -->

                    <div class="row">
                        @if(!empty($cta->dcta_big_image))
                            <div class="col-md-8">
                            @else
                                <div class="col-md-12">
                        @endif

                        @if(isset($cta))


                            <form action="{{ route('cta.update',$cta->id) }}"
                                class="cta-section-wraper-form" enctype="multipart/form-data" method="POST">

                                @csrf
                                @method('Put')

                                <div class="form-group">
                                    <label for="fcta_title">{{ __('messages.Title') }}</label>
                                    <input id="fcta_title" type="text" name="fcta_title" class="form-control"
                                        value="{{ $cta->dcta_title }}">
                                </div>

                                <div class="form-group">
                                    <label for="fcta_title_2">{{ __('messages.Title 2') }}</label>
                                    <textarea id="fcta_title_2" type="text" name="fcta_title_2" class="form-control"
                                        rows="4">{{ $cta->dcta_title_2 }}</textarea>
                                </div>

                                <div class="form-group">
                                    <label for="fcta_btn">{{ __('messages.Button Text') }}</label>
                                    <input id="fcta_btn" type="text" name="fcta_btn" class="form-control"
                                        value="{{ $cta->dcta_btn }}">
                                </div>

                                <div class="form-group">
                                    <label for="fcta_url">{{ __('messages.Button URL') }}</label>
                                    <input id="fcta_url" type="text" name="fcta_url" class="form-control"
                                        value="{{ $cta->dcta_url }}">
                                </div>

                                <div class="form-group">
                                    <label for="fcta_big_image">{{ __('messages.Cta BG Image') }}</label>
                                    <input id="fcta_big_image" type="file" name="fcta_big_image" class="form-control"
                                        value="{{ $cta->dcta_big_image }}">
                                </div>

                                <button type="submit" class="btn btn-primary">{{ __('messages.Update') }}</button>
                                <a href="{{ route('cta.destroy',$cta->id ) }}"
                                    class="btn mb-1 btn-danger">{{ __('messages.Delete') }}</a>

                            </form>

                        @else

                            <form action="{{ route('cta.store') }}" class="cta-section-wraper-form"
                                enctype="multipart/form-data" method="POST">
                                @csrf

                                <div class="form-group">
                                    <label for="fcta_title">{{ __('messages.Title') }}</label>
                                    <input id="fcta_title" type="text" name="fcta_title" class="form-control"
                                        placeholder="{{ __('messages.do you have any project ?') }}" required>
                                </div>

                                <div class="form-group">
                                    <label for="fcta_title_2">{{ __('messages.Title 2') }}</label>
                                    <textarea id="fcta_title_2" type="text" name="fcta_title_2" class="form-control"
                                        rows="4">{{ __('messages.let’s talk about business soluations with us') }}</textarea>
                                </div>

                                <div class="form-group">
                                    <label for="fcta_btn">{{ __('messages.Button Text') }}</label>
                                    <input id="fcta_btn" type="text" name="fcta_btn" class="form-control"
                                        placeholder="{{ __('messages.join with us') }}">
                                </div>

                                <div class="form-group">
                                    <label for="fcta_url">{{ __('messages.Button URL') }}</label>
                                    <input id="fcta_url" type="text" name="fcta_url" class="form-control"
                                        placeholder="{{ __('messages.www.example.com') }}">
                                </div>

                                <div class="form-group">
                                    <label for="fcta_big_image">{{ __('messages.Cta BG Image') }}</label>
                                    <input id="fcta_big_image" type="file" name="fcta_big_image" class="form-control"
                                        required>
                                </div>

                                <button type="submit" class="btn btn-primary">{{ __('messages.Create') }}</button>

                            </form>

                        @endif

                    </div>

                    @if(!empty($cta->dcta_big_image))

                        <div class="col-md-4">
                            @if(!empty($cta->dcta_big_image))

                                <div class="cta-right-image">
                                    <div class="cta-img mb-5">
                                        <h5>{{ __('messages.Cta BG Image') }}</h5>
                            <img class="img-fluid" src="{{ asset($cta->dcta_big_image) }}" alt="img" />
                                    </div>

                                </div>
                            @endif

                        </div>

                    @endif

                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
@endsection