routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'login' => true,
    'register' => true,
    'reset' => false,
    ]);

    Route::middleware(['XSS'])->group(function () {

    //Installation Part

    Route::get('/install','Installer\InstallerController@install')->name('install')->middleware('installer');

    Route::get('/install/info','Installer\InstallerController@info')->name('install.info');
    Route::get('/install/check/{param}','Installer\InstallerController@check')->name('install.check');
    Route::get('pre/install','Installer\InstallerController@preinstall')->name('preinstall');
    Route::post('/install/store','Installer\InstallerController@send');

    //Frontend Part

    Route::get('/', 'SiteController@index')->name('index');
    Route::get('/hearourpoint', 'SiteController@hearourpoint')->name('hearourpoint');
    Route::get('/acc', 'SiteController@acc')->name('acc');
    Route::get('/partner', 'SiteController@partner')->name('partner');
    Route::get('/invest', 'SiteController@invest')->name('invest');
    Route::get('/apply', 'SiteController@apply')->name('apply');
    Route::get('/about', 'SiteController@about')->name('about');
    Route::get('/support', 'SiteController@support')->name('team');
    Route::get('/testimonial', 'SiteController@testimonial')->name('testimonial');
    Route::get('/blog-list', 'SiteController@bloglist')->name('blog-list');
    Route::get('/blog-grid', 'SiteController@bloggrid')->name('blog-grid');
    Route::get('/blogdetails/{id}/{slug}', 'SiteController@blogdetails');
    Route::get('/blog-search','SiteController@blogsearchpage')->name('blog.search');
    Route::get('/contact', 'SiteController@contact')->name('contact');
    Route::post('/frcontact', 'SiteController@frcontactstore')->name('frcontact.store');
    Route::post('/frpartner', 'SiteController@frpartnerstore')->name('frpartner.store');
    Route::post('/frinvest', 'SiteController@frinveststore')->name('frinvest.store');
    Route::post('/fracc', 'SiteController@fraccstore')->name('fracc.store');
    Route::post('/frsubscribe', 'SiteController@frsubscribestore')->name('frsubscribe.store');
});


Route::group(['prefix'=>'admin','middleware'=>['auth','XSS']],function(){

    //Language
    Route::get('lang/{lang}', 'Admin\LanguageController@switchLang')->name('lang.switch');
    // Dashboard
    Route::resource('dashboard', 'Admin\DashboardController');

    // Profile
    Route::resource('profile', 'Admin\ProfileController');
    Route::get('profile/destroy/{id}','Admin\ProfileController@destroy')->name('profile.destroy');

    // General
    Route::resource('general', 'Admin\GeneralController');
    Route::post('general/destroy','Admin\GeneralController@destroy')->name('general.destroy');
    Route::get('general/destroy/{id}','Admin\GeneralController@destroy')->name('general.destroy');

    // Mainslider
    Route::resource('mainslider', 'Admin\MainSliderController');
    Route::get('mainslider/destroy/{id}','Admin\MainSliderController@destroy')->name('mainslider.destroy');

    // About
    Route::resource('about', 'Admin\AboutController');
    Route::get('about/destroy/{id}','Admin\AboutController@destroy')->name('about.destroy');

    // Counter
    Route::resource('counter', 'Admin\CounterController');
    Route::get('counter/destroy/{id}','Admin\CounterController@destroy')->name('counter.destroy');

    // Service
    Route::resource('service', 'Admin\ServiceController');
    Route::get('service/destroy/{id}','Admin\ServiceController@destroy')->name('service.destroy');

    // Service content
    Route::resource('servicecontent', 'Admin\ServiceContentController');
    Route::get('servicecontent/destroy/{id}','Admin\ServiceContentController@destroy')->name('servicecontent.destroy');

    // Team
    Route::resource('team', 'Admin\TeamController');
    Route::get('team/destroy/{id}','Admin\TeamController@destroy')->name('team.destroy');

    // Team content
    Route::resource('teamcontent', 'Admin\TeamContentController');
    Route::get('teamcontent/destroy/{id}','Admin\TeamContentController@destroy')->name('teamcontent.destroy');

    // Cta
    Route::resource('cta', 'Admin\CtaController');
    Route::get('cta/destroy/{id}','Admin\CtaController@destroy')->name('cta.destroy');

    // Testimonial
    Route::resource('testimonial', 'Admin\TestimonialController');
    Route::get('testimonial/destroy/{id}','Admin\TestimonialController@destroy')->name('testimonial.destroy');

    // Testimonial content
    Route::resource('testimonialcontent', 'Admin\TestimonialContentController');
    Route::get('testimonialcontent/destroy/{id}','Admin\TestimonialContentController@destroy')->name('testimonialcontent.destroy');

    // Video
    Route::resource('video', 'Admin\VideoController');
    Route::get('video/destroy/{id}','Admin\VideoController@destroy')->name('video.destroy');

    // Video content
    Route::resource('videocontent', 'Admin\VideoContentController');
    Route::get('videocontent/destroy/{id}','Admin\VideoContentController@destroy')->name('videocontent.destroy');

    // Blog
    Route::resource('blog', 'Admin\BlogController');
    Route::get('blog/destroy/{id}','Admin\BlogController@destroy')->name('blog.destroy');

    // Blog content
    Route::resource('blogcontent', 'Admin\BlogContentController');
    Route::get('blogcontent/destroy/{id}','Admin\BlogContentController@destroy')->name('blogcontent.destroy');

    // Subscribe
    Route::resource('subscribe', 'Admin\SubscribeController');
    Route::get('subscribe/destroy/{id}','Admin\SubscribeController@destroy')->name('subscribe.destroy');

    // Subscribe Content
    Route::resource('subscribecontent', 'Admin\SubscribeContentController');
    Route::get('subscribecontent/destroy/{id}','Admin\SubscribeContentController@destroy')->name('subscribecontent.destroy');

    // Ecosystempartner
    Route::resource('client', 'Admin\ClientController');
    Route::get('client/destroy/{id}','Admin\ClientController@destroy')->name('client.destroy');

    // Widget1
    Route::resource('widget1', 'Admin\Widget1Controller');
    Route::get('widget1/destroy/{id}','Admin\Widget1Controller@destroy')->name('widget1.destroy');

    // Widget2
    Route::resource('widget2', 'Admin\Widget2Controller');
    Route::get('widget2/destroy/{id}','Admin\Widget2Controller@destroy')->name('widget2.destroy');

    // Widget3
    Route::resource('widget3', 'Admin\Widget3Controller');
    Route::get('widget3/destroy/{id}','Admin\Widget3Controller@destroy')->name('widget3.destroy');

    // Contact
    Route::resource('contact', 'Admin\ContactController');
    Route::get('contact/destroy/{id}','Admin\ContactController@destroy')->name('contact.destroy');

    // Contact Info
    Route::resource('contactinfo', 'Admin\ContactinfoController');
    Route::get('contactinfo/destroy/{id}','Admin\ContactinfoController@destroy')->name('contactinfo.destroy');

    // optimizer
    Route::get('optimizer', function() {
        Artisan::call('cache:clear');
        Artisan::call('route:clear');
        Artisan::call('config:clear');
        Artisan::call('view:clear');
        $notification = array(
            'message' => __('messages.Your Site Optimize Successfully'),
            'alert-type' => 'success'
        );
        return redirect()->back()->with($notification);
    });

});

resources/views/admin/footer/widget1.blade.php
@extends('admin.master')
@section('title')
{{ __('messages.Widget1') }}
@endsection
@section('admincontent')

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">{{ __('messages.Widget1 Settings') }}</h4>

                    <!-- Error Start -->
                    @if($errors->any())
                        <ul class="alert alert-danger alert-dismissible fade show mt-5">
                            @foreach($errors->all() as $error)
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    @endif
                    <!-- Error End -->

                    <div class="row">
                        @if(!empty($widget1->dfw1_logo_image))
                            <div class="col-md-8">
                            @else
                                <div class="col-md-12">
                        @endif

                        @if(isset($widget1))


                            <form action="{{ route('widget1.update',$widget1->id) }}"
                                class="widget1-section-wraper-form" enctype="multipart/form-data" method="POST">

                                @csrf
                                @method('Put')


                                <div class="form-group">
                                    <label for="ffw1_logo_image">{{ __('messages.Footer Logo') }}</label>
                                    <input id="ffw1_logo_image" type="file" name="ffw1_logo_image" class="form-control">
                                </div>

                                <div class="form-group">
                                    <label for="ffw1_paragraph">{{ __('messages.About Paragraph') }}</label>
                                    <textarea id="ffw1_paragraph" type="text" name="ffw1_paragraph" class="form-control"
                                        rows="4">{{ $widget1->dfw1_paragraph }}</textarea>
                                </div>

                                <div class="form-group">
                                    <label for="ffw1_social_icon_1">{{ __('messages.Social Icon 1') }}</label>
                                    <input id="ffw1_social_icon_1" type="text" name="ffw1_social_icon_1"
                                        class="form-control" value="{{ $widget1->dfw1_social_icon_1 }}">
                                </div>

                                <div class="form-group">
                                    <label for="ffw1_social_icon_1_link">{{ __('messages.Social Icon 1 Link') }}</label>
                                    <input id="ffw1_social_icon_1_link" type="text" name="ffw1_social_icon_1_link"
                                        class="form-control" value="{{ $widget1->dfw1_social_icon_1_link }}">
                                </div>

                                <div class="form-group">
                                    <label for="ffw1_social_icon_2">{{ __('messages.Social Icon 2') }}</label>
                                    <input id="ffw1_social_icon_2" type="text" name="ffw1_social_icon_2"
                                        class="form-control" value="{{ $widget1->dfw1_social_icon_2 }}">
                                </div>

                                <div class="form-group">
                                    <label for="ffw1_social_icon_2_link">{{ __('messages.Social Icon 2 Link') }}</label>
                                    <input id="ffw1_social_icon_2_link" type="text" name="ffw1_social_icon_2_link"
                                        class="form-control" value="{{ $widget1->dfw1_social_icon_2_link }}">
                                </div>

                                <div class="form-group">
                                    <label for="ffw1_social_icon_3">{{ __('messages.Social Icon 3') }}</label>
                                    <input id="ffw1_social_icon_3" type="text" name="ffw1_social_icon_3"
                                        class="form-control" value="{{ $widget1->dfw1_social_icon_3 }}">
                                </div>

                                <div class="form-group">
                                    <label for="ffw1_social_icon_3_link">{{ __('messages.Social Icon 3 Link') }}</label>
                                    <input id="ffw1_social_icon_3_link" type="text" name="ffw1_social_icon_3_link"
                                        class="form-control" value="{{ $widget1->dfw1_social_icon_3_link }}">
                                </div>

                                <div class="form-group">
                                    <label for="ffw1_social_icon_4">{{ __('messages.Social Icon 4') }}</label>
                                    <input id="ffw1_social_icon_4" type="text" name="ffw1_social_icon_4"
                                        class="form-control" value="{{ $widget1->dfw1_social_icon_4 }}">
                                </div>

                                <div class="form-group">
                                    <label for="ffw1_social_icon_4_link">{{ __('messages.Social Icon 4 Link') }}</label>
                                    <input id="ffw1_social_icon_4_link" type="text" name="ffw1_social_icon_4_link"
                                        class="form-control" value="{{ $widget1->dfw1_social_icon_4_link }}">
                                </div>
                                <button type="submit" class="btn btn-primary">{{ __('messages.Update') }}</button>
                                <a href="{{ route('widget1.destroy',$widget1->id ) }}"
                                    class="btn mb-1 btn-danger">{{ __('messages.Delete') }}</a>

                            </form>
                        @else


                            <form action="{{ route('widget1.store') }}"
                                class="widget1-section-wraper-form" enctype="multipart/form-data" method="POST">
                                @csrf

                                <div class="form-group">
                                    <label for="ffw1_logo_image">{{ __('messages.Footer Logo') }}</label>
                                    <input id="ffw1_logo_image" type="file" name="ffw1_logo_image" class="form-control"
                                        required>
                                </div>

                                <div class="form-group">
                                    <label for="ffw1_paragraph">{{ __('messages.About Paragraph') }}</label>
                                    <textarea id="ffw1_paragraph" type="text" name="ffw1_paragraph" class="form-control"
                                        rows="4">{{ __("messages.There are many variations of but the majority have suffered inject’s humour, or randomised word and don't look even slightly believable. If you are going to use") }}</textarea>
                                </div>

                                <div class="form-group">
                                    <label for="ffw1_social_icon_1">{{ __('messages.Social Icon 1') }}</label>
                                    <input id="ffw1_social_icon_1" type="text" name="ffw1_social_icon_1"
                                        class="form-control" placeholder="{{ __('messages.fa fa-facebook') }}">
                                </div>

                                <div class="form-group">
                                    <label for="ffw1_social_icon_1_link">{{ __('messages.Social Icon 1 Link') }}</label>
                                    <input id="ffw1_social_icon_1_link" type="text" name="ffw1_social_icon_1_link"
                                        class="form-control" placeholder="{{ __('messages.www.example.com') }}">
                                </div>

                                <div class="form-group">
                                    <label for="ffw1_social_icon_2">{{ __('messages.Social Icon 2') }}</label>
                                    <input id="ffw1_social_icon_2" type="text" name="ffw1_social_icon_2"
                                        class="form-control" placeholder="{{ __('messages.fa fa-twitter') }}">
                                </div>

                                <div class="form-group">
                                    <label for="ffw1_social_icon_2_link">{{ __('messages.Social Icon 2 Link') }}</label>
                                    <input id="ffw1_social_icon_2_link" type="text" name="ffw1_social_icon_2_link"
                                        class="form-control" placeholder="{{ __('messages.www.example.com') }}">
                                </div>

                                <div class="form-group">
                                    <label for="ffw1_social_icon_3">{{ __('messages.Social Icon 3') }}</label>
                                    <input id="ffw1_social_icon_3" type="text" name="ffw1_social_icon_3"
                                        class="form-control" placeholder="{{ __('messages.fa fa-instagram') }}">
                                </div>

                                <div class="form-group">
                                    <label for="ffw1_social_icon_3_link">{{ __('messages.Social Icon 3 Link') }}</label>
                                    <input id="ffw1_social_icon_3_link" type="text" name="ffw1_social_icon_3_link"
                                        class="form-control" placeholder="{{ __('messages.www.example.com') }}">
                                </div>

                                <div class="form-group">
                                    <label for="ffw1_social_icon_4">{{ __('messages.Social Icon 4') }}</label>
                                    <input id="ffw1_social_icon_4" type="text" name="ffw1_social_icon_4"
                                        class="form-control" placeholder="{{ __('messages.fa fa-vk') }}">
                                </div>

                                <div class="form-group">
                                    <label for="ffw1_social_icon_4_link">{{ __('messages.Social Icon 4 Link') }}</label>
                                    <input id="ffw1_social_icon_4_link" type="text" name="ffw1_social_icon_4_link"
                                        class="form-control" placeholder="{{ __('messages.www.example.com') }}">
                                </div>

                                <button type="submit" class="btn btn-primary">{{ __('messages.Create') }}</button>

                            </form>

                        @endif

                    </div>
                    @if(!empty($widget1->dfw1_logo_image))
                        <div class="col-md-4">

                            <div class="widget1-right-image">

                                <div class="widget1-icon mb-5">
                                    <h5>{{ __('messages.Footer Logo') }}</h5>

                                    <img class="img-fluid" src="{{ asset( $widget1->dfw1_logo_image ) }}"
                                        alt="img" />
                                </div>

                            </div>

                        </div>
                    @endif

                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
@endsection

resources/views/admin/footer/widget2.blade.php
@extends('admin.master')
@section('title')
{{ __('messages.Quick Link') }}
@endsection
@section('admincontent')

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <!-- Error Start -->
                    @if($errors->any())
                        <ul class="alert alert-danger alert-dismissible fade show mt-5">
                            @foreach($errors->all() as $error)
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    @endif
                    <!-- Error End -->

                    <h4 class="card-title">
                        {{ __('messages.Link Table') }}
                        <button type="button" class="btn btn-primary float-right" data-toggle="modal"
                            data-target="#widget2modal">{{ __('messages.Create Link') }}</button>
                    </h4>
                    <!-- modal start -->
                    <!-- Modal -->
                    <div class="modal fade" id="widget2modal" tabindex="-1" role="dialog" aria-labelledby="modaltitle"
                        aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="modaltitle">{{ __('messages.Create Link') }}</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <!-- Modal Body Contant Start -->
                                    <form action="{{ route('widget2.store') }}"
                                        class="create-widget2-form-wraper" method="POST" enctype="multipart/form-data">
                                        @csrf

                                        <div class="form-group">
                                            <label for="fwidget2_text">{{ __('messages.Title') }}</label>
                                            <input id="fwidget2_text" type="text" name="fwidget2_text"
                                                class="form-control" placeholder="{{ __('messages.Your Title Here') }}" required>
                                        </div>

                                        <div class="form-group">
                                            <label for="fwidget2_link">{{ __('messages.Link') }}</label>
                                            <input id="fwidget2_link" type="text" name="fwidget2_link"
                                                class="form-control" placeholder="{{ __('messages.www.example.com') }}">
                                        </div>

                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary"
                                                data-dismiss="modal">{{ __('messages.Close') }}</button>
                                            <button type="submit" class="btn btn-primary">{{ __('messages.Save') }}</button>
                                        </div>
                                    </form>

                                    <!-- Modal Body Contant End -->
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- modal end -->
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered zero-configuration">
                            <thead>
                                <tr>
                                    <th>{{ __('messages.No') }}</th>
                                    <th>{{ __('messages.Title') }}</th>
                                    <th>{{ __('messages.Link') }}</th>
                                    <th>{{ __('messages.Action') }}</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($widget2 as $key=> $item)

                                    <tr>
                                        <td>{{ $key+1 }}</td>
                                        <td>{{ $item->dwidget2_text }}</td>
                                        <td>{{ $item->dwidget2_link }}</td>
                                        <td>
                                            <span>

                                                <button type="button" class="btn mb-1 btn-primary modal-title"
                                                    data-toggle="modal" data-target="#Widget2ditModal{{ $key }}">
                                                    <i class="fa fa-pencil color-muted m-r-5"></i>
                                                </button>


                                                <a href="{{ route('widget2.destroy',$item->id) }}"
                                                    class="btn mb-1 btn-danger"><i
                                                        class="fa fa-close color-danger"></i></a>
                                            </span>
                                        </td>
                                    </tr>

                                    <!-- widget2 Edit Modal -->
                                    <div class="modal fade" id="Widget2ditModal{{ $key }}" tabindex="-1" role="dialog"
                                        aria-labelledby="editmodaltitle" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="editmodaltitle">{{ __('messages.Edit widget2') }}</h5>
                                                    <button type="button" class="close" data-dismiss="modal"
                                                        aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <!-- Modal Body Contant Start -->
                                                    <form class="create-widget2-form-wraper" method="POST"
                                                        action="{{ route('widget2.update',$item->id) }}"
                                                        enctype="multipart/form-data" enctype="multipart/form-data">
                                                        @csrf
                                                        @method('PUT')

                                                        <div class="form-group">
                                                            <label for="fwidget2_text">{{ __('messages.Title') }}</label>
                                                            <input id="fwidget2_text" type="text" name="fwidget2_text"
                                                                class="form-control" value="{{ $item->dwidget2_text }}">
                                                        </div>

                                                        <div class="form-group">
                                                            <label for="fwidget2_link">{{ __('messages.Link') }}</label>
                                                            <input id="fwidget2_link" type="text" name="fwidget2_link"
                                                                class="form-control"
                                                                value="{{ $item->dwidget2_link }}">
                                                        </div>

                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-secondary"
                                                                data-dismiss="modal">{{ __('messages.Close') }}</button>
                                                            <button type="submit" class="btn btn-primary">{{ __('messages.Save') }}</button>
                                                        </div>
                                                    </form>
                                                    <!-- Modal Body Contant End -->
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- widget2 Edit Modal -->
                                @endforeach

                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>{{ __('messages.No') }}</th>
                                    <th>{{ __('messages.Title') }}</th>
                                    <th>{{ __('messages.Link') }}</th>
                                    <th>{{ __('messages.Action') }}</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
@endsection